### ISSUE TITLE
Rack application timed out during boot

### ISSUE THREAD

**Issue by dinhhuydh** [hashrocket/capybara-webmock#16]
Hi, 
My cucumber takes so long so i'm trying to avoid the external requests (js files) when running cucumber. After i install the gem with the configuration, the scenario raises exception `Rack application timed out during boot`.
Below is my application:

Rails is `4.2.1` 
Capabara is `2.7.1`.
Rack is `1.6.5`

Cucumber is set up:
```
Capybara.app_host = "http://app.lvh.me:31337"
Capybara.server_host = "app.lvh.me"
Capybara.server_port = "31337"

require 'capybara/webmock'
Capybara.javascript_driver = :capybara_webmock_chrome
Capybara::Webmock.port_number = "31337"
Capybara::Webmock.start

at_exit do
  Capybara::Webmock.stop
end
```

As I dig out, the code stop at `capybara-2.7.1/lib/capybara/server.rb:82`
`res = Net::HTTP.start(host, @port) { |http| http.get('/__identify__') }`

Besides, when i commented the line in `Webmock.start:16` method, the scenario passes
`IO.popen("PROXY_PORT_NUMBER=#{port_number} rackup #{proxy_file} >> #{log_file} 2>&1")`
  
Not sure i miss any configuration to make it work with Chrome driver. Let me know if i need to supply any more information.

Thanks,

**Comment by dillonhafer** [comment]
This is due to `Capybara::Webmock` gem and your rails app trying to use the same port.

You don't want to have `Capybara::Webmock.port_number` be the same as your `Capybara.server_port`. The configuration `Capybara::Webmock.port_number` is the port the gem will use to spin up a proxy server to intercept requests. Usually you don't need to set `Capybara::Webmock.port_number`.

I hope this helps. Please let me know if you still have questions.

**Comment by dinhhuydh** [comment]
Thanks for your quick response.
You're right. However when `Capybara::Webmock.port_number` is not set as the same as `Capybara.server_port`, the request is not handled properly. Although the browser runs but the page does not display correctly. The log is below. As i looked at the codebase, i guess that the proxy setting might not be correctly in `lib/capybara/webmock.rb`.
`Capybara::Selenium::Driver.new(app, browser: :chrome, switches: Capybara::Webmock.chrome_switches)`
The chrome driver now uses `desired_capabilities` with Selenium::WebDriver::Remote::Capabilities (https://sites.google.com/a/chromium.org/chromedriver/capabilities) to set proxy. Please correct me if i'm wrong.

```
Completed 200 OK in 768ms (Views: 747.3ms | ActiveRecord: 0.3ms)
127.0.0.1 - - [18/Apr/2017:22:18:03 ICT] "GET http://app.lvh.me:31337/signin HTTP/1.1" 200 9795
- -> http://app.lvh.me:31337/signin
[2017-04-18 22:18:04] ERROR TypeError: can't dup NilClass
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httprequest.rb:393:in `dup'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httprequest.rb:393:in `meta_vars'
        /Users/huy/.rvm/gems/ruby-2.3.1@tinypulse/gems/rack-1.6.5/lib/rack/handler/webrick.rb:62:in `service'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
[2017-04-18 22:18:04] ERROR TypeError: can't dup NilClass
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httprequest.rb:393:in `dup'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httprequest.rb:393:in `meta_vars'
        /Users/huy/.rvm/gems/ruby-2.3.1@tinypulse/gems/rack-1.6.5/lib/rack/handler/webrick.rb:62:in `service'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /Users/huy/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
127.0.0.1 - - [18/Apr/2017:22:18:04 ICT] "GET http://cdn.optimizely.com/js/2757820323.js HTTP/1.1" 200 0
127.0.0.1 - - [18/Apr/2017:22:18:04 ICT] "CONNECT fonts.googleapis.com:443 HTTP/1.1" 500 309
http://app.lvh.me:31337/signin -> http://cdn.optimizely.com/js/2757820323.js
- -> fonts.googleapis.com:443
127.0.0.1 - - [18/Apr/2017:22:18:04 ICT] "CONNECT fonts.googleapis.com:443 HTTP/1.1" 500 309
- -> fonts.googleapis.com:443
Started GET "/assets/lib/jquery-1.8.3.min.self.js?body=1" for 127.0.0.1 at 2017-04-18 22:18:04 +0700
```

**Comment by dillonhafer** [comment]
If your version of the chrome driver is not compatible with the settings defined in `Capybara::Webmock`'s chrome driver, you can try writing your own driver to see if it fixes your issue. If it does, I would appreciate seeing what you come up with, and maybe add it to the gem. Here is an example on writing your own capybara driver to support your chromedriver:

```ruby
Capybara.register_driver :my_custom_capybara_webmock_driver do |app|
  # Change the switches option to the new option. I'm not sure
  # what it is in your case. desired_capabilities?
  my_options = {desired_capabilities: '--proxy-address=127.0.0.1:9292'}
  Capybara::Selenium::Driver.new(app, browser: :chrome, switches: my_options)
end
```

And then in your cucumber config you can use your custom driver with: 

```
Capybara.javascript_driver = :my_custom_capybara_webmock_driver
```
