### ISSUE TITLE
Is this project related to the webmock gem?

### ISSUE THREAD

**Issue by zedtux** [hashrocket/capybara-webmock#20]
I have a project where I'm trying to find a way to test Braintree payment gateway using Cucumber and I'm facing an issue in mocking the servers calls.

When I saw the name `capybara-webmock` I was thinking of having a proxy server, using Webmock in the middle, in order to mock the web calls from the web browser but it doesn't seem to be the case when I look at the project's dependencies.

So is this gem related to webmock and allow call mocking (meaning being able to defines the server's answer)?

And if not, would it be possible to add it, and would it be hard and long dev, or not?

The project where I'm trying to make Cucumber testing Braintree is here: https://github.com/zedtux/cucumber-braintree

**Comment by dillonhafer** [comment]
It currently does not do the mocking yet, mocking has been a planned feature from the beginning, and we planned on using the webmock gem's library/syntax for declaring mocked responses. We just haven't add that feature yet.

**Comment by zedtux** [comment]
Thank you for the answer @dillonhafer.

Do you have any kind of plan to implement it or not?
(It should be clearly said in the README.md file in my opinion.)

**Comment by iamgollum** [comment]
zedtux, swell-investing opened up a PR which looked promising. I was actually extending some of there functionality for the company I work for to include mocking as CORS was failing for this library but we chose to go with https://github.com/oesmith/puffing-billy. I would check that out for your needs.

**Comment by zedtux** [comment]
Thank you @iamgollum for your comment, I already know that gem, and my [cucumber-braintree](https://github.com/zedtux/cucumber-braintree) repo is using it with VCR but my test pass the first time (without any fixture files) but then fails the second time (with fixture files).
That's why I'm looking for other options...
