### ISSUE TITLE
No way to override `ALLOWED_HOSTS`

### ISSUE THREAD

**Issue by jejacks0n** [hashrocket/capybara-webmock#35]
I'd like to add a single host because we have an iframe loaded on some pages that we haven't been able to isolate and resolve yet. But there seems to be no way to inject into this value because it's hardcoded and how the proxy server is started it's not possible to override.

**Comment by atd** [comment]
Fixed at https://github.com/i4a/capybara-webmock/commit/0fc15dc5472afad8ebde39441083ed9ed3aec6f6

I can prepare a proper pull request if there is interest

**Comment by dillonhafer** [comment]
Fixed in #42 expected to drop in version 0.6.0 on rubygems sometime this week
