### ISSUE TITLE
Loading external resources anyway

### ISSUE THREAD

**Issue by elalemanyo** [hashrocket/capybara-webmock#37]
Hi,
Maybe I am doing something wrong or I expect something that is not going to happen 🤷‍♂️
I add the gem and I have configured it as explained in the documentation:

```ruby
require "capybara/webmock"

RSpec.configure do |config|
  config.before(:each) do |example|
    if example.metadata[:type] == :feature
      Capybara::Webmock.start
    end
  end

  Capybara.javascript_driver = :capybara_webmock_chrome_headless
  Capybara.server_port = 9292

  config.after(:suite) do
    Capybara::Webmock.stop
  end
end
```

After I run same tests locally without headless mode, so I can see in chrome browser what is going on. And all images from external resources still loading, I am doing something wrong?

Thanks in advance!

**Comment by dillonhafer** [comment]
What driver were you using?

**Comment by elalemanyo** [comment]
@dillonhafer I am using `:capybara_webmock_chrome_headless`

**Comment by dillonhafer** [comment]
I meant, what driver were you using for the non-headless mode (e.g. `:capybara_webmock_chrome`)

**Comment by elalemanyo** [comment]
@dillonhafer I am doing something like this:
```ruby
  browser_options = ::Selenium::WebDriver::Chrome::Options.new.tap do |opts|
    # opts.args << "--headless"
    opts.args << "--disable-gpu"
    opts.args << "--window-size=1440,900"
  end

  Capybara.register_driver :headless_chrome do |app|
    Capybara::Selenium::Driver.load_selenium
    Capybara::Selenium::Driver.new(app, browser: :chrome, options: browser_options, desired_capabilities: chrome_capabilities)
  end

  Capybara.javascript_driver = :capybara_webmock_chrome_headless
```

As you see I just need to comment `opts.args << "--headless"` to see the browser. Not sure if my config is ok.

**Comment by dillonhafer** [comment]
Your driver is missing the proxy settings:

`options.add_argument "--proxy-server=127.0.0.1:#{port_number}"`

You can reference the build-in drivers that this gem provides for reference: https://github.com/hashrocket/capybara-webmock/blob/master/lib/capybara/webmock.rb#L172-L186
