### ISSUE TITLE
Is there a way to mock the external dependencies?

### ISSUE THREAD

**Issue by RichardConroy** [hashrocket/capybara-webmock#47]
Perhaps I am misunderstanding the purpose here but is there a way to specify an alternative response to `""` for intercepted / proxied requests?

I am thinking of true mocking (a la Webmock) where you could specify the actual response to 3rd party services like payment providers (my use case).

**Comment by dillonhafer** [comment]
That was the intended purpose. I never got far enough to implement this. I think are some other branches/forks that may allow this. I haven't been able to work on this project for many years.
